eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discovery-server-prod:9000/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true

server:
  port: 10052

spring:
  application:
    name: basketService
  redis:
    host: basket-db-prod
    port: 6379

