eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discovery-server-prod:9000/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true

server:
  port: 10054
  
spring:
  application:
    name: identityService
  datasource:
    url: jdbc:postgresql://identity-db-prod:5432/CRMIdentityServiceDB
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validation:
            mode: none
    show-sql: true

jwt:
  secret:
    key: de6ef0886c5f568751a0cb7f6f560982b93c05c26b8897632fab03d2b36ca84e5f9ff73422cd0974ae43f3faafc59346baeb507df71110e9d53aa3af9643db39
  expiration.time: 600000
